{
 "title": "Linux Host Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Utilisation",
   "type": "graph",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "legendFormat": "user",
     "expr": "sum by (host) (rate(namedprocess_namegroup_cpu_seconds_total{group=\"user\"}[2m]))"
    },
    {
     "expr": "sum by (host) (rate(namedprocess_namegroup_cpu_seconds_total{group=\"system\"}[2m]))",
     "legendFormat": "system"
    },
    {
     "expr": "sum by (host) (rate(namedprocess_namegroup_cpu_seconds_total{group=\"iowait\"}[2m]))",
     "legendFormat": "iowait"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "graph",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "legendFormat": "used",
     "expr": "sum by (host) (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes)"
    },
    {
     "expr": "sum by (host) (node_memory_MemAvailable_bytes)",
     "legendFormat": "available"
    }
   ]
  },
  {
   "title": "Network Utilisation (bytes)",
   "type": "graph",
   "gridPos": { "x": 0, "y": 9, "w": 24, "h": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "legendFormat": "received",
     "expr": "sum by (host) (rate(node_network_receive_bytes_total[2m]))"
    },
    {
     "expr": "sum by (host) (rate(node_network_transmit_bytes_total[2m]))",
     "legendFormat": "transmitted"
    }
   ]
  }
 ]
}